services:
  - type: web
    name: api
    env: python
    plan: free
    envVars:
      - key: APP_PORT
        value: 8000
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py


  - type: web
    name: client-page
    env: python
    plan: free
    envVars:
      - key: API_BASE
        value: https://api-hw8n.onrender.com
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run client_page/client_webform.py --server.port=8501

  - type: web
    name: manager-page
    env: python
    plan: free
    envVars:
      - key: API_BASE
        value: https://api-hw8n.onrender.com
      - key: AUTH_IP_ADDR
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run manager_page/manager_page.py --server.port=8502


version: "1"